// Generated by build.py -- do not edit by hand.
window.GALLERY = {
  "logo": "logo.png",
  "topics": [
    {
      "id": "procrastination",
      "name": "Procrastination & Motivation"
    },
    {
      "id": "screen-time",
      "name": "Screen Time & Doomscrolling"
    },
    {
      "id": "focus",
      "name": "Focus & Distraction"
    },
    {
      "id": "studying",
      "name": "Studying & Homework"
    },
    {
      "id": "time-management",
      "name": "Time Management & Organization"
    },
    {
      "id": "sleep",
      "name": "Sleep"
    },
    {
      "id": "food",
      "name": "Healthy Eating"
    }
  ],
  "classes": [
    {
      "id": "seavey",
      "teacher": "Mr. Seavey",
      "blocks": [
        {
          "block": "C",
          "apps": [
            {
              "name": "FocusShield",
              "tagline": "Ultimate Screen Time & Accountability System",
              "students": "Ben & Emiliana",
              "path": "seavey/C/ben-emiliana.html",
              "topics": [
                "screen-time"
              ],
              "studentLabel": "Screen Time"
            },
            {
              "name": "Socratic Study Notebook",
              "tagline": "9th Grade Multi-Subject Edition",
              "students": "David & Bea",
              "path": "seavey/C/david-bea.html",
              "topics": [
                "studying"
              ],
              "studentLabel": "Studying"
            },
            {
              "name": "FocusFlow",
              "tagline": "Mindful Focus Workspace",
              "students": "Ema & Enkhlen",
              "path": "seavey/C/ema-enkhlen.html",
              "topics": [
                "procrastination"
              ],
              "studentLabel": "procrastination"
            },
            {
              "name": "Studify",
              "tagline": "Smart Planner & AI Tutor",
              "students": "Mateo & Viti",
              "path": "seavey/C/mateo-viti.html",
              "topics": [
                "procrastination"
              ],
              "studentLabel": "Procrastination"
            }
          ]
        },
        {
          "block": "D",
          "apps": [
            {
              "name": "FocusTab V1.0",
              "tagline": "Homework Companion & SMART Goal Hub",
              "students": "Carter & Jungmin",
              "path": "seavey/D/carter-jungmin.html",
              "topics": [
                "procrastination",
                "studying"
              ],
              "studentLabel": "Procrastination and Studying"
            },
            {
              "name": "StudySync",
              "tagline": "Student Planner, Reminders & Practice Tests",
              "students": "Daniela & Thomas",
              "path": "seavey/D/daniela-thomas.html",
              "topics": [
                "time-management"
              ],
              "studentLabel": "Organize and time manage"
            },
            {
              "name": "FocusPulse",
              "tagline": "",
              "students": "Felix & Malene",
              "path": "seavey/D/felix-malene.html",
              "topics": [
                "procrastination",
                "time-management"
              ],
              "studentLabel": "Procrastination, Motivation, Time Management"
            },
            {
              "name": "FocusLaunch",
              "tagline": "Put Down Your Phone & Study",
              "students": "Jaco & Elise",
              "path": "seavey/D/jaco-elise.html",
              "topics": [
                "studying"
              ],
              "studentLabel": "study"
            },
            {
              "name": "Homework Motivator & Organizer",
              "tagline": "",
              "students": "Jaewan & Camila",
              "path": "seavey/D/jaewan-camila.html",
              "topics": [
                "procrastination",
                "time-management"
              ],
              "studentLabel": "Time managment and Motivation"
            },
            {
              "name": "Nourish & Rest",
              "tagline": "Sleep & Healthy Eating Companion",
              "students": "Neven & Antonia",
              "path": "seavey/D/neven-antonia.html",
              "topics": [
                "sleep",
                "food"
              ],
              "studentLabel": "Sleep/Food"
            },
            {
              "name": "FocusNest",
              "tagline": "Zero Distraction Homework Engine",
              "students": "Olivia & Kai",
              "path": "seavey/D/olivia-kai.html",
              "topics": [
                "procrastination",
                "studying"
              ],
              "studentLabel": "get started on homework"
            },
            {
              "name": "FocusGrade",
              "tagline": "Homework & Focus Manager",
              "students": "Renato & Kentaro",
              "path": "seavey/D/renato-kentaro.html",
              "topics": [
                "procrastination"
              ],
              "studentLabel": "Procrastinating"
            },
            {
              "name": "StudyQuest",
              "tagline": "After-School Focus, Virtual Pet & Practice Hub",
              "students": "Xinyue, Arnaud & Josefina",
              "path": "seavey/D/xinyue-arnaud-josefina.html",
              "topics": [
                "procrastination"
              ],
              "studentLabel": "procrastination"
            }
          ]
        }
      ]
    },
    {
      "id": "cade",
      "teacher": "Ms. Cade",
      "blocks": [
        {
          "block": "A",
          "apps": [
            {
              "name": "FocusPulse",
              "tagline": "Bright Rainbow & Unicorn Edition",
              "students": "Agustina, Beatrix & Ryo",
              "path": "cade/A/agustina-beatrix-ryo.html",
              "topics": [
                "procrastination",
                "screen-time",
                "sleep"
              ],
              "studentLabel": "Sleep, Procrastination, Doomscrool"
            },
            {
              "name": "MindBento 🫰",
              "tagline": "Focus & Anti-Procrastination Hub",
              "students": "Anni & Nicolas",
              "path": "cade/A/anni-nicolas.html",
              "topics": [
                "procrastination"
              ],
              "studentLabel": "Procrastination"
            },
            {
              "name": "Time Quest",
              "tagline": "HW & SMART Goal Companion",
              "students": "Julian & Micah",
              "path": "cade/A/julian-micah.html",
              "topics": [
                "procrastination"
              ],
              "studentLabel": "Procrastination"
            },
            {
              "name": "Focus Arcade",
              "tagline": "Doomscroll Destroyer",
              "students": "Matias & Julieta",
              "path": "cade/A/matias-julieta.html",
              "topics": [
                "screen-time"
              ],
              "studentLabel": "Help doomscrolling"
            },
            {
              "name": "SlumberQuest",
              "tagline": "Sleep & Study Routine Tracker",
              "students": "Olivia & Diego",
              "path": "cade/A/olivia-diego.html",
              "topics": [
                "sleep"
              ],
              "studentLabel": "Sleep"
            },
            {
              "name": "NightShift & Focus",
              "tagline": "Teen Night Routine & Homework Assistant",
              "students": "Orlando & Lucas",
              "path": "cade/A/orlando-lucas.html",
              "topics": [
                "screen-time",
                "focus",
                "sleep"
              ],
              "studentLabel": "sleep,doom scroll; sleep focus"
            },
            {
              "name": "DreamSlice",
              "tagline": "AI Sleep & Pizza Rewards",
              "students": "Shanying & Sophia",
              "path": "cade/A/shanying-sophia.html",
              "topics": [
                "focus",
                "sleep"
              ],
              "studentLabel": "sleep and concentration"
            }
          ]
        },
        {
          "block": "B",
          "apps": [
            {
              "name": "Cozy Homework Studio",
              "tagline": "",
              "students": "Ale & Olivia",
              "path": "cade/B/ale-olivia.html",
              "topics": [
                "procrastination",
                "time-management"
              ],
              "studentLabel": "Procrastination and time management"
            },
            {
              "name": "Athlete Rest & Habit Tracker",
              "tagline": "",
              "students": "Ariel & Justin",
              "path": "cade/B/ariel-justin.html",
              "topics": [
                "sleep"
              ],
              "studentLabel": "Sleep"
            },
            {
              "name": "FocusForge Pitchside",
              "tagline": "Pro Soccer Student Athlete System",
              "students": "Arsene & Timothe",
              "path": "cade/B/arsene-timothe.html",
              "topics": [
                "studying"
              ],
              "studentLabel": "homework"
            },
            {
              "name": "WarmFocus",
              "tagline": "Unwind & Homework Companion",
              "students": "Augusto & Eugene",
              "path": "cade/B/augusto-eugene.html",
              "topics": [
                "procrastination"
              ],
              "studentLabel": "Procrastination"
            },
            {
              "name": "Periwinkle & Rose",
              "tagline": "Olivia & Ale's Aesthetic Focus Studio",
              "students": "Chelsey, Isabella & Jiani",
              "path": "cade/B/chelsey-isabella-jiani.html",
              "topics": [
                "procrastination"
              ],
              "studentLabel": "Procrastination/activity tracking"
            },
            {
              "name": "Water Polo Homework & Focus Hub",
              "tagline": "",
              "students": "Diego & Josefina",
              "path": "cade/B/diego-josefina.html",
              "topics": [
                "screen-time"
              ],
              "studentLabel": "doomscrolling, sports"
            },
            {
              "name": "KICK-IN // Futuristic Homework & Focus Tracker",
              "tagline": "",
              "students": "Martin & Sasha",
              "path": "cade/B/martin-sasha.html",
              "topics": [
                "sleep"
              ],
              "studentLabel": "Sleep"
            }
          ]
        }
      ]
    },
    {
      "id": "kim",
      "teacher": "Ms. Kim",
      "blocks": [
        {
          "block": "H",
          "apps": [
            {
              "name": "NutriHydro",
              "tagline": "Balanced Nutrition & Hydration Companion",
              "students": "Benja & Xuran",
              "path": "kim/H/benja-xuran.html",
              "topics": [
                "food"
              ],
              "studentLabel": "eating drinking"
            },
            {
              "name": "FocusQuest",
              "tagline": "Simple 9th Grade Study Companion",
              "students": "Jacobo, Joshua & Alejandra",
              "path": "kim/H/jacobo-joshua-alejandra.html",
              "topics": [
                "studying"
              ],
              "studentLabel": "Studying more"
            },
            {
              "name": "PIVOT x NoxRest",
              "tagline": "AI-Verified Mindful Dopamine Rewire",
              "students": "Lucas, Pedro & Rebecca",
              "path": "kim/H/lucas-pedro-rebecca.html",
              "topics": [
                "screen-time"
              ],
              "studentLabel": "doomscrolling"
            },
            {
              "name": "FocusPal",
              "tagline": "Screen Time & Focus Sanctuary",
              "students": "Santi, Atharva & Inaki",
              "path": "kim/H/santi-atharva-inaki.html",
              "topics": [
                "screen-time"
              ],
              "studentLabel": "doom scrolling"
            }
          ]
        }
      ]
    }
  ]
};
